application: theitalianbay
version: 1
runtime: python27
api_version: 4
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon
- url: /api/.+
  script: handlers.main.app
- url: .*
  static_files: static/html/index.html
  upload: static/html/index.html
  
builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
