application: theitalianbay
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/vnd.microsoft.icon
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: .*
  script: handlers.main.app
  
builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
